global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'yaku'
    static_configs:
      - targets: ['172.16.48.10:9100']

  - job_name: 'modbus_exporter'
    static_configs:
      - targets: ['172.16.48.127:9101']